#!/bin/bash

jupyter labextension install @jupyter-widgets/jupyterlab-manager qgrid

# for classic notebook, use instead:
jupyter nbextension enable --py --sys-prefix qgrid
jupyter nbextension enable --py --sys-prefix widgetsnbextension
